---
- name: Add Prometheus Helm repository
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    state: present

- name: Update Helm Chart Repositories
  ansible.builtin.command: helm repo update

- name: Install Kube-Prometheus Stack
  community.kubernetes.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    values:
      prometheus:
        prometheusSpec:
          retention: 5d # Example of setting a custom value