---
k3s_version: v1.22.3+k3s1
ansible_user: "{{ vault_data.remote_user }}"
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['kube_server'][0]]['ansible_host'] | default(groups['kube_server'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
ansible_ssh_private_key_file: "{{ vault_data.private_key_file }}"