---
- name: Add Rook Helm Chart Repository
  community.kubernetes.helm_repository:
    name: rook-release
    repo_url: https://charts.rook.io/release
    state: present

- name: Update Helm Chart Repositories
  ansible.builtin.command: helm repo update

- name: Install Rook Operator via Helm
  community.kubernetes.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    release_namespace: rook-ceph
    create_namespace: true

- name: Install Rook Ceph Cluster via Helm
  community.kubernetes.helm:
    name: rook-ceph-cluster
    chart_ref: rook-release/rook-ceph-cluster
    release_namespace: rook-ceph
    create_namespace: true
    values:
      config: |
        storage:
          useAllNodes: true
          useAllDevices: true
          # specify deviceFilter if you want to limit to certain devices
          # deviceFilter: /dev/sd[b-e]
          # specify nodes if you want to limit the use of nodes
          # nodes:
          #   - name: "node-name"
          #     devices:
          #       - name: "vdb"