all:
  children:
    proxmox:
        hosts:
          pve1:
            ansible_host: 192.168.1.184
    vms:
      children:
        k3s_cluster:
          children:
            kube_server:
              hosts:
                server_1:
                  ansible_host: 192.168.1.41
                server_2:
                  ansible_host: 192.168.1.42
                server_3:
                  ansible_host: 192.168.1.43
            kube_agents:
              hosts:
                agent_1:
                  ansible_host: 192.168.1.51
                agent_2:
                  ansible_host: 192.168.1.52
                agent_3:
                  ansible_host: 192.168.1.53
            kube_storage:
              hosts:
                storage_1:
                  ansible_host: 192.168.1.61
